package com.myspace.loan_approval;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Applicant implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Age")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label(value = "Credit Score")
	private java.lang.Integer creditScore;
	@org.kie.api.definition.type.Label(value = "Monthly Income")
	private java.lang.Double monthlyIncome;
	@org.kie.api.definition.type.Label(value = "Yearly Income")
	private java.lang.Double yearlyIncome;
	@org.kie.api.definition.type.Label(value = "Name")
	private java.lang.String name;

	public Applicant() {
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.Integer getCreditScore() {
		return this.creditScore;
	}

	public void setCreditScore(java.lang.Integer creditScore) {
		this.creditScore = creditScore;
	}

	public java.lang.Double getMonthlyIncome() {
		return this.monthlyIncome;
	}

	public void setMonthlyIncome(java.lang.Double monthlyIncome) {
		this.monthlyIncome = monthlyIncome;
	}

	public java.lang.Double getYearlyIncome() {
		return this.yearlyIncome;
	}

	public void setYearlyIncome(java.lang.Double yearlyIncome) {
		this.yearlyIncome = yearlyIncome;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public Applicant(java.lang.Integer age, java.lang.Integer creditScore,
			java.lang.Double monthlyIncome, java.lang.Double yearlyIncome,
			java.lang.String name) {
		this.age = age;
		this.creditScore = creditScore;
		this.monthlyIncome = monthlyIncome;
		this.yearlyIncome = yearlyIncome;
		this.name = name;
	}

}